//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affirmations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Affirmations.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions, problems or suggestions, catch me via e-mail.
        /// </summary>
        public static string AboutDialogContents {
            get {
                return ResourceManager.GetString("AboutDialogContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppbarAdd {
            get {
                return ResourceManager.GetString("AppbarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppbarCancel {
            get {
                return ResourceManager.GetString("AppbarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string AppbarDelete {
            get {
                return ResourceManager.GetString("AppbarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish.
        /// </summary>
        public static string AppbarFinish {
            get {
                return ResourceManager.GetString("AppbarFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppbarMenuItemAbout {
            get {
                return ResourceManager.GetString("AppbarMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string AppbarMenuItemRateAndReview {
            get {
                return ResourceManager.GetString("AppbarMenuItemRateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppbarMenuItemSettings {
            get {
                return ResourceManager.GetString("AppbarMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string AppbarNext {
            get {
                return ResourceManager.GetString("AppbarNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string AppbarPrevious {
            get {
                return ResourceManager.GetString("AppbarPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat now.
        /// </summary>
        public static string AppbarRepeat {
            get {
                return ResourceManager.GetString("AppbarRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppbarSave {
            get {
                return ResourceManager.GetString("AppbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affirmations.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFFIRMATIONS.
        /// </summary>
        public static string ApplicationTitleCapitalized {
            get {
                return ResourceManager.GetString("ApplicationTitleCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affirmations.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedAtLabel {
            get {
                return ResourceManager.GetString("CreatedAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT AFFIRMATION.
        /// </summary>
        public static string EditAffirmationCapitalized {
            get {
                return ResourceManager.GetString("EditAffirmationCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I treat my dreams as my plans..
        /// </summary>
        public static string ExampleAffirmation1 {
            get {
                return ResourceManager.GetString("ExampleAffirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyday is a great opportunity to experience something unbelievable..
        /// </summary>
        public static string ExampleAffirmation2 {
            get {
                return ResourceManager.GetString("ExampleAffirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s me who decide how my life looks like..
        /// </summary>
        public static string ExampleAffirmation3 {
            get {
                return ResourceManager.GetString("ExampleAffirmation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My time is here and now..
        /// </summary>
        public static string ExampleAffirmation4 {
            get {
                return ResourceManager.GetString("ExampleAffirmation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can achieve anything I want..
        /// </summary>
        public static string ExampleAffirmation5 {
            get {
                return ResourceManager.GetString("ExampleAffirmation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The way I feel depends only on me..
        /// </summary>
        public static string ExampleAffirmation6 {
            get {
                return ResourceManager.GetString("ExampleAffirmation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures are only feedback..
        /// </summary>
        public static string ExampleAffirmation7 {
            get {
                return ResourceManager.GetString("ExampleAffirmation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the tile above to repeat your affirmations..
        /// </summary>
        public static string FirstRepetitionLabel {
            get {
                return ResourceManager.GetString("FirstRepetitionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve repeated your affirmations.
        /// </summary>
        public static string LastRepetitionDateLabel {
            get {
                return ResourceManager.GetString("LastRepetitionDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat affirmations.
        /// </summary>
        public static string LiveTileTitle {
            get {
                return ResourceManager.GetString("LiveTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW AFFIRMATION.
        /// </summary>
        public static string NewAffirmationCapitalized {
            get {
                return ResourceManager.GetString("NewAffirmationCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily repetition reminders are.
        /// </summary>
        public static string NoRemindersLabel {
            get {
                return ResourceManager.GetString("NoRemindersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string PivotListTitle {
            get {
                return ResourceManager.GetString("PivotListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string PivotWelcomeTitle {
            get {
                return ResourceManager.GetString("PivotWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t repeated your affirmations today..
        /// </summary>
        public static string ReminderContent {
            get {
                return ResourceManager.GetString("ReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you forget about repetition, I&apos;ll let you know at.
        /// </summary>
        public static string ReminderTimeLabel {
            get {
                return ResourceManager.GetString("ReminderTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off..
        /// </summary>
        public static string RepetitionTimeOffLabel {
            get {
                return ResourceManager.GetString("RepetitionTimeOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string SettingsRemindersLabel {
            get {
                return ResourceManager.GetString("SettingsRemindersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder time.
        /// </summary>
        public static string SettingsReminderTimeLabel {
            get {
                return ResourceManager.GetString("SettingsReminderTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s empty in here. Add affirmations using the button on the bottom..
        /// </summary>
        public static string WelcomePivotPlaceholder {
            get {
                return ResourceManager.GetString("WelcomePivotPlaceholder", resourceCulture);
            }
        }
    }
}
